update_config:
  enabled: true
  update_branch_format: version-update/{0}
  labels:
    - version-update
  pr_reviewers:
    - epam-avramenko

branches:
  - RANCHER-2520-test:
      enabled: true
      need_pr: false
      pre_release: "only"
      descriptor_build_offset: "100200000000000"
  - R1-2025:
      enabled: true
      need_pr: true
      pre_release: "false"